apiVersion: v1
kind: Service
metadata:
  name: db-headless-service
  labels:
    app: mysql-db-service
spec:
  ports:
  - port: 3306
    name: db-deployment
  clusterIP: None
  selector:
    app: mysql-db-service